# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HumanLearning' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HumanLearning
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'FirebaseAuth'
pod 'FirebaseStorage'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'FirebaseDatabase'

  target 'HumanLearningTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HumanLearningUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
